"""Update schemas for workout Progress Aggregation

Revision ID: 027cef12d0fa
Revises: 8d6b7d0f4b1a
Create Date: 2026-05-31 22:53:02.062578
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401

revision = "027cef12d0fa"
down_revision = "8d6b7d0f4b1a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
