"""upgradeclear

Revision ID: 06954bbd4a89
Revises: af4b47a74048
Create Date: 2026-06-06 11:54:37.137137
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401



revision = '06954bbd4a89'
down_revision = 'af4b47a74048'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
