"""Update schemas

Revision ID: 131b846a5dcf
Revises: c63234f39eb7
Create Date: 2026-06-04 15:04:37.614337
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401



revision = '131b846a5dcf'
down_revision = 'c63234f39eb7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
