"""Update schemas for exercise feature

Revision ID: 1b1bcfcb6c11
Revises: 29e919321fd4
Create Date: 2026-05-31 17:44:24.569689
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401

from sqlalchemy.dialects import postgresql

revision = '1b1bcfcb6c11'
down_revision = '29e919321fd4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'exercises',
        sa.Column(
            'secondary_muscles',
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )
    op.add_column('exercises', sa.Column('movement_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('exercises', sa.Column('instruction', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True))
    op.add_column('exercises', sa.Column('safety_notes', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True))
    op.add_column(
        'exercises',
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')),
    )
    op.create_index(op.f('ix_exercises_movement_type'), 'exercises', ['movement_type'], unique=False)
    op.alter_column('exercises', 'secondary_muscles', server_default=None)
    op.alter_column('exercises', 'is_active', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercises_movement_type'), table_name='exercises')
    op.drop_column('exercises', 'is_active')
    op.drop_column('exercises', 'safety_notes')
    op.drop_column('exercises', 'instruction')
    op.drop_column('exercises', 'movement_type')
    op.drop_column('exercises', 'secondary_muscles')
    # ### end Alembic commands ###
