"""Update schemas for DatatypeMismatchError

Revision ID: 29e919321fd4
Revises: 24c8f2d55960
Create Date: 2026-05-31 17:08:48.727333
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401

from sqlalchemy.dialects import postgresql

revision = "29e919321fd4"
down_revision = "24c8f2d55960"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_preferences",
        "preferred_workout_days",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        type_=sa.JSON().with_variant(postgresql.ARRAY(sa.Text()), "postgresql"),
        existing_nullable=False,
    )
    op.alter_column(
        "user_preferences",
        "dislikes",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        type_=sa.JSON().with_variant(postgresql.ARRAY(sa.Text()), "postgresql"),
        existing_nullable=False,
    )
    op.alter_column(
        "user_preferences",
        "metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
    )
    op.alter_column(
        "user_profiles",
        "injuries",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        type_=sa.JSON().with_variant(postgresql.ARRAY(sa.Text()), "postgresql"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_profiles",
        "injuries",
        existing_type=sa.JSON().with_variant(postgresql.ARRAY(sa.Text()), "postgresql"),
        type_=postgresql.ARRAY(sa.VARCHAR()),
        existing_nullable=False,
    )
    op.alter_column(
        "user_preferences",
        "metadata",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "user_preferences",
        "dislikes",
        existing_type=sa.JSON().with_variant(postgresql.ARRAY(sa.Text()), "postgresql"),
        type_=postgresql.ARRAY(sa.VARCHAR()),
        existing_nullable=False,
    )
    op.alter_column(
        "user_preferences",
        "preferred_workout_days",
        existing_type=sa.JSON().with_variant(postgresql.ARRAY(sa.Text()), "postgresql"),
        type_=postgresql.ARRAY(sa.VARCHAR()),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
