"""Update schemas for AI Workout plan

Revision ID: 486a84cd5034
Revises: e24cb468487f
Create Date: 2026-05-31 23:15:40.723965
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401

revision = "486a84cd5034"
down_revision = "e24cb468487f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
