"""Update schemas for rule base workout

Revision ID: 59f0a3a6d305
Revises: 1b1bcfcb6c11
Create Date: 2026-05-31 22:17:00.108889
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401

revision = "59f0a3a6d305"
down_revision = "1b1bcfcb6c11"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workout_plan_exercises", sa.Column("target_weight", sa.Float(), nullable=True)
    )
    op.add_column(
        "workout_plan_exercises", sa.Column("rest_seconds", sa.Integer(), nullable=True)
    )
    op.add_column(
        "workout_plans",
        sa.Column(
            "target_date",
            sa.Date(),
            nullable=False,
            server_default=sa.text("CURRENT_DATE"),
        ),
    )
    op.add_column(
        "workout_plans",
        sa.Column(
            "goal",
            sqlmodel.sql.sqltypes.AutoString(length=50),
            nullable=False,
            server_default=sa.text("'general_health'"),
        ),
    )
    op.add_column(
        "workout_plans",
        sa.Column("estimated_duration_minutes", sa.Integer(), nullable=True),
    )
    op.add_column(
        "workout_plans",
        sa.Column(
            "ai_reasoning_summary",
            sqlmodel.sql.sqltypes.AutoString(length=2000),
            nullable=True,
        ),
    )
    op.add_column(
        "workout_plans",
        sa.Column(
            "safety_note", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True
        ),
    )
    op.create_index(
        op.f("ix_workout_plans_goal"), "workout_plans", ["goal"], unique=False
    )
    op.create_index(
        op.f("ix_workout_plans_target_date"),
        "workout_plans",
        ["target_date"],
        unique=False,
    )
    op.alter_column("workout_plans", "target_date", server_default=None)
    op.alter_column("workout_plans", "goal", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workout_plans_target_date"), table_name="workout_plans")
    op.drop_index(op.f("ix_workout_plans_goal"), table_name="workout_plans")
    op.drop_column("workout_plans", "safety_note")
    op.drop_column("workout_plans", "ai_reasoning_summary")
    op.drop_column("workout_plans", "estimated_duration_minutes")
    op.drop_column("workout_plans", "goal")
    op.drop_column("workout_plans", "target_date")
    op.drop_column("workout_plan_exercises", "rest_seconds")
    op.drop_column("workout_plan_exercises", "target_weight")
    # ### end Alembic commands ###
