"""Update schemas

Revision ID: 5f3079b87003
Revises: ce8966daa376
Create Date: 2026-06-10 15:53:31.084299
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401



revision = '5f3079b87003'
down_revision = 'ce8966daa376'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
