"""Update schemas

Revision ID: 66d8843d18a2
Revises: 6fbb93881284
Create Date: 2026-06-05 11:58:09.846899
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401



revision = '66d8843d18a2'
down_revision = '6fbb93881284'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
