"""Update schemas

Revision ID: 6c2459993615
Revises: 6f22053743a1
Create Date: 2026-06-10 09:39:35.143217
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401



revision = '6c2459993615'
down_revision = '6f22053743a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
