"""Update schemas

Revision ID: 734790b99211
Revises: 77ad5ddd7160
Create Date: 2026-06-05 15:45:52.937300
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401



revision = '734790b99211'
down_revision = '77ad5ddd7160'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
