"""Update schemas

Revision ID: 77ad5ddd7160
Revises: c4a91f72e6d3
Create Date: 2026-06-05 15:09:28.855299
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401



revision = '77ad5ddd7160'
down_revision = 'c4a91f72e6d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('training_programs', 'training_style',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_profiles', 'training_style',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'training_style',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'balanced'::character varying"),
               existing_nullable=False)
    op.alter_column('training_programs', 'training_style',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'balanced'::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###
