"""Update schemas

Revision ID: 7cc355bb248d
Revises: c4452158b179
Create Date: 2026-06-10 16:46:25.330344
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401



revision = '7cc355bb248d'
down_revision = 'c4452158b179'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
