"""Update schemas

Revision ID: 9b3064af791c
Revises: b8f1b2c3d4e5
Create Date: 2026-06-02 21:06:23.009950
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401

from sqlalchemy.dialects import postgresql

revision = "9b3064af791c"
down_revision = "b8f1b2c3d4e5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ai_requests",
        "provider",
        existing_type=sa.VARCHAR(length=50),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "ai_requests",
        "model_name",
        existing_type=sa.VARCHAR(length=100),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "ai_requests", "prompt", existing_type=sa.VARCHAR(length=4000), nullable=True
    )
    op.alter_column(
        "ai_requests",
        "input_payload",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "ai_requests",
        "output_payload",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "ai_requests",
        "fallback_used",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "ai_usage_daily",
        "ai_workout_count",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "ai_usage_daily",
        "ai_chat_count",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "ai_usage_daily",
        "ai_replacement_count",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "ai_usage_daily",
        "ai_weekly_report_count",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "ai_usage_daily",
        "total_ai_count",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ai_usage_daily",
        "total_ai_count",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.alter_column(
        "ai_usage_daily",
        "ai_weekly_report_count",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.alter_column(
        "ai_usage_daily",
        "ai_replacement_count",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.alter_column(
        "ai_usage_daily",
        "ai_chat_count",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.alter_column(
        "ai_usage_daily",
        "ai_workout_count",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.alter_column(
        "ai_requests",
        "fallback_used",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.alter_column(
        "ai_requests",
        "output_payload",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=sa.text("'{}'::jsonb"),
        existing_nullable=False,
    )
    op.alter_column(
        "ai_requests",
        "input_payload",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=sa.text("'{}'::jsonb"),
        existing_nullable=False,
    )
    op.alter_column(
        "ai_requests", "prompt", existing_type=sa.VARCHAR(length=4000), nullable=False
    )
    op.alter_column(
        "ai_requests",
        "model_name",
        existing_type=sa.VARCHAR(length=100),
        server_default=sa.text("''::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "ai_requests",
        "provider",
        existing_type=sa.VARCHAR(length=50),
        server_default=sa.text("'gemini'::character varying"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
