"""Update schemas

Revision ID: af4b47a74048
Revises: d2f41a8c9e70
Create Date: 2026-06-05 20:06:27.892251
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401

from sqlalchemy.dialects import postgresql

revision = 'af4b47a74048'
down_revision = 'd2f41a8c9e70'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'movement_limitations',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_profiles', 'pain_areas',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_profiles', 'pain_movements',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'pain_movements',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               server_default=sa.text("'{}'::text[]"),
               existing_nullable=False)
    op.alter_column('user_profiles', 'pain_areas',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               server_default=sa.text("'{}'::text[]"),
               existing_nullable=False)
    op.alter_column('user_profiles', 'movement_limitations',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               server_default=sa.text("'{}'::text[]"),
               existing_nullable=False)
    # ### end Alembic commands ###
