"""Update schemas

Revision ID: b9783f2374be
Revises: 7cc355bb248d
Create Date: 2026-06-10 16:50:06.930537
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401



revision = 'b9783f2374be'
down_revision = '7cc355bb248d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
