"""Update schemas

Revision ID: c4452158b179
Revises: 5f3079b87003
Create Date: 2026-06-10 16:19:54.142797
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401



revision = 'c4452158b179'
down_revision = '5f3079b87003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
