"""Update schemas

Revision ID: c63234f39eb7
Revises: 7f3c9d2a1b6e
Create Date: 2026-06-02 22:07:23.809690
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401



revision = 'c63234f39eb7'
down_revision = '7f3c9d2a1b6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
