"""Update schemas

Revision ID: ce8966daa376
Revises: 8f5a1c2d9b77
Create Date: 2026-06-10 12:19:03.367041
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401



revision = 'ce8966daa376'
down_revision = '8f5a1c2d9b77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
