"""Update schemas for workout Progress Aggregation

Revision ID: e24cb468487f
Revises: 027cef12d0fa
Create Date: 2026-05-31 22:58:22.111515
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401



revision = 'e24cb468487f'
down_revision = '027cef12d0fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
