"""Update schemas

Revision ID: e3b0c6458a2e
Revises: e7aeb6159714
Create Date: 2026-06-05 11:13:55.956645
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401



revision = 'e3b0c6458a2e'
down_revision = 'e7aeb6159714'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
