"""Update schemas

Revision ID: e7aeb6159714
Revises: 131b846a5dcf
Create Date: 2026-06-05 09:04:28.947177
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401



revision = 'e7aeb6159714'
down_revision = '131b846a5dcf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
