from dataclasses import dataclass, field


@dataclass(frozen=True, slots=True)
class WorkoutSlot:
    slot_type: str
    movement_patterns: list[str]
    primary_muscles: list[str]
    exercise_roles: list[str]
    required: bool
    min_sets: int
    max_sets: int
    reps: str
    rest_seconds: int
    target_rpe: int
    max_candidates: int = 1


@dataclass(frozen=True, slots=True)
class WorkoutTemplate:
    id: str
    title: str
    focus_type: str
    goal_tags: list[str] = field(default_factory=list)
    slots: list[WorkoutSlot] = field(default_factory=list)


def slot(
    slot_type: str,
    movement_patterns: list[str],
    primary_muscles: list[str],
    exercise_roles: list[str],
    required: bool,
    sets: int | tuple[int, int],
    reps: str,
    rest_seconds: int,
    target_rpe: int,
    max_candidates: int = 1,
) -> WorkoutSlot:
    min_sets, max_sets = sets if isinstance(sets, tuple) else (sets, sets)
    return WorkoutSlot(
        slot_type=slot_type,
        movement_patterns=movement_patterns,
        primary_muscles=primary_muscles,
        exercise_roles=exercise_roles,
        required=required,
        min_sets=min_sets,
        max_sets=max_sets,
        reps=reps,
        rest_seconds=rest_seconds,
        target_rpe=target_rpe,
        max_candidates=max_candidates,
    )


BUILT_IN_TEMPLATES: dict[str, WorkoutTemplate] = {
    "upper_pull_emphasis": WorkoutTemplate(
        id="upper_pull_emphasis",
        title="Upper Body Pull Emphasis",
        focus_type="upper_body_pull",
        goal_tags=["muscle_gain", "strength", "general_health"],
        slots=[
            slot(
                "main_horizontal_pull",
                ["horizontal_pull"],
                ["back"],
                ["main_compound"],
                True,
                3,
                "8-12",
                90,
                7,
            ),
            slot(
                "secondary_back",
                ["horizontal_pull", "vertical_pull"],
                ["back"],
                ["secondary_compound"],
                True,
                3,
                "10-12",
                90,
                7,
            ),
            slot(
                "push_balance",
                ["horizontal_push"],
                ["chest"],
                ["main_compound", "secondary_compound"],
                True,
                3,
                "8-15 or AMRAP",
                75,
                7,
            ),
            slot(
                "rear_delt_posture",
                ["rear_delt"],
                ["shoulders"],
                ["corrective", "isolation"],
                True,
                3,
                "12-15",
                60,
                7,
            ),
            slot(
                "biceps_accessory",
                ["elbow_flexion"],
                ["arms"],
                ["accessory", "isolation"],
                True,
                3,
                "10-12",
                60,
                7,
            ),
            slot(
                "cardio_finisher",
                ["cardio"],
                ["cardio"],
                ["finisher"],
                False,
                10,
                "30s fast / 60s easy",
                60,
                7,
            ),
        ],
    ),
    "upper_push_emphasis": WorkoutTemplate(
        id="upper_push_emphasis",
        title="Upper Body Push Emphasis",
        focus_type="upper_body_push",
        goal_tags=["muscle_gain", "strength", "general_health"],
        slots=[
            slot(
                "main_horizontal_push",
                ["horizontal_push"],
                ["chest"],
                ["main_compound"],
                True,
                3,
                "8-12",
                90,
                7,
            ),
            slot(
                "secondary_push",
                ["vertical_push", "horizontal_push"],
                ["shoulders", "chest"],
                ["secondary_compound"],
                True,
                3,
                "8-12",
                90,
                7,
            ),
            slot(
                "pull_balance",
                ["horizontal_pull"],
                ["back"],
                ["secondary_compound"],
                True,
                3,
                "10-12",
                75,
                7,
            ),
            slot(
                "lateral_raise_or_rear_delt",
                ["rear_delt", "vertical_push"],
                ["shoulders"],
                ["accessory", "isolation", "corrective"],
                True,
                3,
                "12-15",
                60,
                7,
            ),
            slot(
                "triceps_accessory",
                ["elbow_extension"],
                ["arms"],
                ["accessory", "isolation"],
                True,
                3,
                "10-12",
                60,
                7,
            ),
            slot(
                "optional_cardio",
                ["cardio"],
                ["cardio"],
                ["finisher"],
                False,
                8,
                "30s fast / 60s easy",
                60,
                7,
            ),
        ],
    ),
    "balanced_upper": WorkoutTemplate(
        id="balanced_upper",
        title="Balanced Upper Body",
        focus_type="upper_body",
        goal_tags=["muscle_gain", "general_health"],
        slots=[
            slot(
                "horizontal_push",
                ["horizontal_push"],
                ["chest"],
                ["main_compound", "secondary_compound"],
                True,
                3,
                "8-12",
                90,
                7,
            ),
            slot(
                "horizontal_pull",
                ["horizontal_pull"],
                ["back"],
                ["main_compound", "secondary_compound"],
                True,
                3,
                "8-12",
                90,
                7,
            ),
            slot(
                "vertical_push",
                ["vertical_push"],
                ["shoulders"],
                ["main_compound", "secondary_compound"],
                True,
                3,
                "8-12",
                75,
                7,
            ),
            slot(
                "vertical_pull",
                ["vertical_pull"],
                ["back"],
                ["secondary_compound"],
                True,
                3,
                "10-12",
                75,
                7,
            ),
            slot(
                "arms_or_shoulders",
                ["elbow_flexion", "elbow_extension", "rear_delt"],
                ["arms", "shoulders"],
                ["accessory", "isolation"],
                True,
                3,
                "10-15",
                60,
                7,
            ),
            slot(
                "optional_cardio",
                ["cardio"],
                ["cardio"],
                ["finisher"],
                False,
                8,
                "30s fast / 60s easy",
                60,
                7,
            ),
        ],
    ),
    "lower_body_strength": WorkoutTemplate(
        id="lower_body_strength",
        title="Lower Body Strength",
        focus_type="lower_body",
        goal_tags=["muscle_gain", "strength"],
        slots=[
            slot(
                "squat_or_leg_press",
                ["squat"],
                ["legs"],
                ["main_compound"],
                True,
                3,
                "6-10",
                120,
                7,
            ),
            slot(
                "hinge",
                ["hinge"],
                ["legs"],
                ["main_compound", "secondary_compound"],
                True,
                3,
                "8-10",
                120,
                7,
            ),
            slot(
                "unilateral_leg",
                ["lunge"],
                ["legs"],
                ["secondary_compound", "accessory"],
                True,
                3,
                "8-10 each side",
                90,
                7,
            ),
            slot(
                "hamstring_or_glute_accessory",
                ["hinge"],
                ["legs"],
                ["accessory"],
                True,
                3,
                "10-12",
                75,
                7,
            ),
            slot(
                "core",
                ["core"],
                ["core"],
                ["accessory", "corrective"],
                True,
                3,
                "30-45 seconds",
                60,
                7,
            ),
            slot(
                "optional_cardio",
                ["cardio"],
                ["cardio"],
                ["finisher"],
                False,
                8,
                "30s fast / 60s easy",
                60,
                7,
            ),
        ],
    ),
    "full_body_beginner": WorkoutTemplate(
        id="full_body_beginner",
        title="Full Body Beginner",
        focus_type="full_body",
        goal_tags=["general_health", "muscle_gain", "fat_loss"],
        slots=[
            slot(
                "squat",
                ["squat"],
                ["legs"],
                ["main_compound", "secondary_compound"],
                True,
                3,
                "8-12",
                75,
                7,
            ),
            slot(
                "horizontal_push",
                ["horizontal_push"],
                ["chest"],
                ["main_compound", "secondary_compound"],
                True,
                3,
                "8-12",
                75,
                7,
            ),
            slot(
                "horizontal_pull",
                ["horizontal_pull"],
                ["back"],
                ["main_compound", "secondary_compound"],
                True,
                3,
                "8-12",
                75,
                7,
            ),
            slot(
                "hinge_or_glute",
                ["hinge"],
                ["legs"],
                ["secondary_compound", "accessory"],
                True,
                3,
                "10-12",
                75,
                7,
            ),
            slot(
                "core",
                ["core"],
                ["core"],
                ["accessory", "corrective"],
                True,
                2,
                "30-45 seconds",
                60,
                7,
            ),
            slot(
                "light_cardio",
                ["cardio"],
                ["cardio"],
                ["finisher"],
                False,
                6,
                "Easy 5-10 minutes",
                45,
                6,
            ),
        ],
    ),
    "recovery_session": WorkoutTemplate(
        id="recovery_session",
        title="Recovery Session",
        focus_type="mobility",
        goal_tags=["recovery", "general_health"],
        slots=[
            slot(
                "mobility",
                ["mobility"],
                ["mobility"],
                ["corrective"],
                True,
                1,
                "5-8 minutes",
                30,
                3,
            ),
            slot(
                "easy_cardio",
                ["cardio"],
                ["cardio"],
                ["corrective"],
                True,
                1,
                "10-20 minutes easy",
                30,
                3,
            ),
            slot(
                "core_or_stability",
                ["core"],
                ["core"],
                ["corrective"],
                True,
                2,
                "30-45 seconds",
                45,
                3,
            ),
            slot(
                "stretching",
                ["mobility"],
                ["mobility"],
                ["corrective"],
                False,
                1,
                "5 minutes",
                30,
                3,
            ),
        ],
    ),
}
